---
name: deploy

on:
  push:
    branches:
      - devel

jobs:
  build-html:
    runs-on: ubuntu-latest
    defaults:
    steps:
      - name: Checkout git
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
          with:
            python-version: '3.x'

      - name: Install requirments
        run: python -m pip install -r requirements.txt

      - name: Build HTML
        run: make -C docs/ singlehtml

      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs/_build/singlehtml/
